### ISSUE TITLE
Fix the broken links

### ISSUE THREAD

**Issue by pedabraham** [zudochkin/awesome-newsletters#149]
I was checking the repository and found some broken links and I would like to delete all the broken links. Should I make a pull request for every broken link? or Should I make only one pull request with all the broken links?

**Comment by ferhatelmas** [comment]
@pedabraham IMHO, one PR for all makes sense.

**Comment by pedabraham** [comment]
Hi, I already delete all the bad links in #151. There's a link, https://angel.co/newsletters, which awesome_bot says is a 403, but in my tests this link shows a 200 in some cases, and in chrome seems fine, so I did not modify this link in any way.
