### ISSUE TITLE
Add: Future Crunch

### ISSUE THREAD

**Issue by GwynHannay** [zudochkin/awesome-newsletters#200]
Hey! Suggestion for a newsletter to add: [Future Crunch](https://futurecrunch.com).

I came across them a couple of years ago as they focus on delivering all of the good news that we generally don't get to hear because we're bombarded with all of the bad. [Here's](https://futurecrunch.com/good-news-ebola-electric-trucks-super-reserve) an example of an email you'd get.

They do a big one at the end of the year with all the good things that happened that year.

News is generally divided into sections as general, science, and environment.

**Comment by ferhatelmas** [comment]
looks like a fit, feel free to PR
