### ISSUE TITLE
Incorrect link for Baeldung Weekly Review

### ISSUE THREAD

**Issue by Nawaz027** [zudochkin/awesome-newsletters#226]
Under Java section Baeldung Weekly Review doesn't seems to have the option to subscribe the newsletter. It shows only the previous issues of it. We can choose to update the link to https://www.baeldung.com/java-web-weekly .

**Comment by zudochkin** [comment]
@Nawaz027 can you please make a PR for that?

**Comment by Nawaz027** [comment]
sure.

**Comment by ferhatelmas** [comment]
fixed in https://github.com/zudochkin/awesome-newsletters/pull/227
